/*
SQLyog Community v13.1.6 (64 bit)
MySQL - 10.4.16-MariaDB : Database - housing
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`housing` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;

USE `housing`;

/*Table structure for table `apartments` */

DROP TABLE IF EXISTS `apartments`;

CREATE TABLE `apartments` (
  `APARTMENT_ID` int(10) NOT NULL AUTO_INCREMENT,
  `APARTMENT_TITLE` varchar(100) NOT NULL,
  `APARTMENT_UNIVERSITY` varchar(70) DEFAULT NULL,
  `APARTMENT_AREA` int(10) DEFAULT NULL,
  `APARTMENT_DESCRIPTION` mediumtext DEFAULT NULL,
  `APARTMENT_FLOOR` varchar(30) DEFAULT NULL,
  `APARTMENT_ROOMS` varchar(30) DEFAULT NULL,
  `APARTMENT_BATHROOMS` varchar(30) DEFAULT NULL,
  `APARTMENT_PRICE` int(10) DEFAULT NULL,
  `APARTMENT_IMG` varchar(1000) DEFAULT NULL,
  `APARTMENT_FURNISHED` varchar(15) DEFAULT NULL,
  `APARTMENT_RENTAL` varchar(20) DEFAULT NULL,
  `USER_ID_FK` int(10) DEFAULT NULL,
  `OWNER_NAME` varchar(20) DEFAULT NULL,
  `OWNER_PHONE` varchar(15) DEFAULT NULL,
  PRIMARY KEY (`APARTMENT_ID`),
  KEY `USER_ID_FK` (`USER_ID_FK`),
  CONSTRAINT `USER_ID_FK` FOREIGN KEY (`USER_ID_FK`) REFERENCES `users` (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4;

/*Data for the table `apartments` */

insert  into `apartments`(`APARTMENT_ID`,`APARTMENT_TITLE`,`APARTMENT_UNIVERSITY`,`APARTMENT_AREA`,`APARTMENT_DESCRIPTION`,`APARTMENT_FLOOR`,`APARTMENT_ROOMS`,`APARTMENT_BATHROOMS`,`APARTMENT_PRICE`,`APARTMENT_IMG`,`APARTMENT_FURNISHED`,`APARTMENT_RENTAL`,`USER_ID_FK`,`OWNER_NAME`,`OWNER_PHONE`) values 
(2,'philedelphia','Philadelphia University',100,'in jerash','ground floor','1 bedroom','1 bathroom',130,'','furnished','monthly',2,'abed zakebah','0796666685');

/*Table structure for table `users` */

DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
  `USER_ID` int(10) NOT NULL AUTO_INCREMENT,
  `USER_FNAME` varchar(15) NOT NULL,
  `USER_LNAME` varchar(15) NOT NULL,
  `USER_BIRTH` date DEFAULT NULL,
  `USER_PHONE` varchar(15) NOT NULL,
  `USER_EMAIL` varchar(30) NOT NULL,
  `USER_PASSWORD` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `USER_PHONE` (`USER_PHONE`),
  UNIQUE KEY `USER_EMAIL` (`USER_EMAIL`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4;

/*Data for the table `users` */

insert  into `users`(`USER_ID`,`USER_FNAME`,`USER_LNAME`,`USER_BIRTH`,`USER_PHONE`,`USER_EMAIL`,`USER_PASSWORD`) values 
(1,'ahmad','nserat','1999-03-11','0790906192','ahmadnserat150@gmail.com','123456'),
(2,'abed','zakebah','1999-01-05','0796666685','abedzakebah@gmail.com','abed');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
